[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
locker = "76Hqr9nixY17jLcLekWAnmnAQLdSYS9DuU3XErVfETi3"

[programs.testnet]
locker = "LockvXm2nWht6EvHf44AmCuS3eMKRiWTuks2x27XRRo"

[programs.mainnet]
locker = "LockvXm2nWht6EvHf44AmCuS3eMKRiWTuks2x27XRRo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = ".keys/authority.json"

[clusters.testnet]
url = "https://testnet.fogo.io"

[clusters.mainnet]
url = "https://mainnet.fogo.io"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "EBZDYx7599krFc4m2govwBdZcicr4GgepqC78m71nsHS"
program = "artifacts/transfer_hook_counter.so"