name: Generate Anchor IDL
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering
jobs:
  generate-idl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.91.0"
      - uses: Swatinem/rust-cache@v2
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v2.3.13/install)"
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Install Anchor CLI via avm
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --force
          avm install 0.31.1
          avm use 0.31.1
          echo "/home/runner/.avm/bin" >> $GITHUB_PATH
      - run: anchor build
      - name: Move idl.json
        run: |
          mv target/idl/locker.json ./sdk/artifacts/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update IDL"
          # only add generated locker.json file
          add-paths: |
            sdk/artifacts/locker.json
          # branch name, see https://github.com/marketplace/actions/create-pull-request#action-behaviour
          branch: idl
          # always create unique branch name, see https://github.com/marketplace/actions/create-pull-request#alternative-strategy---always-create-a-new-pull-request-branch
          branch-suffix: timestamp
